server:
  port: 5000
spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=profit-genie;sendStringParametersAsUnicode=false
    username: programmer
    password: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: profitgenie88@gmail.com
    password: profitgenie_1234
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.ssl.trust: smtp.gmail.com






#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

  liquibase:
    enabled: false


