spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=profit-genie;sendStringParametersAsUnicode=false
    username: programmer
    password: test
